### ISSUE TITLE
Try expanding message input window when messages exceed 2 lines

### ISSUE THREAD

**Issue by edgarfinn** [FACN1/week1-javiasy#35]
Currently, any long messages are hard to read in full, the user needs to scroll

**Comment by macintoshhelper** [comment]
This appears to be a CSS limitation. "height: auto;" doesn't do anything. If there's time, we could add a JavaScript hack to correct it.

**Comment by macintoshhelper** [comment]
Semi-fixed this by increasing height to 80px. It won't auto-expand, but will have more height than the other inputs.
